---
- include: install.yml

- name: Stop ntpd service (rhel)
  service:
    name: ntpd
    state: stopped
  when: (ansible_distribution != "Debian" and ansible_distribution != "Ubuntu")
  tags: ntpdate-run
  ignore_errors: true

- name: Stop ntpd service (deb)
  service:
    name: ntp
    state: stopped
  when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
  tags: ntpdate-run
  ignore_errors: true

- name: Execute ntpdate runs
  ansible.builtin.command: "ntpdate -s {{ ntpdate_server|default('0.pool.ntp.org') }}"
  notify:
    - start ntpd (rhel)
    - start ntpd (deb)
  with_sequence: count="{{ ntpdate_runs|int }}"
  tags: ntpdate-run
